import json
import sys

def json_to_netscape(json_path, netscape_path):
    with open(json_path, 'r', encoding='utf-8') as f:
        cookies = json.load(f)
    
    with open(netscape_path, 'w', encoding='utf-8') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file is generated by json_to_netscape.py\n\n")
        
        for cookie in cookies:
            domain = cookie.get('domain', '')
            # Netscape format requires domain to start with . for subdomains
            # if not domain.startswith('.'):
            #     domain = '.' + domain
            
            flag = 'TRUE' if domain.startswith('.') else 'FALSE'
            path = cookie.get('path', '/')
            secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
            
            # Expiration
            expiration = cookie.get('expirationDate', 0)
            if not expiration:
                 expiration = cookie.get('expiry', 0)
            if not expiration:
                 # If no expiry, use a far future date or 0 (session)
                 # But yt-dlp might prefer a number. Let's look for 'session'
                 if cookie.get('session', False):
                     expiration = 0
                 else:
                     expiration = 2147483647 # 2038
            
            name = cookie.get('name', '')
            value = cookie.get('value', '')
            
            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{int(expiration)}\t{name}\t{value}\n")

    print(f"Converted {json_path} to {netscape_path}")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python convert_cookies.py <json_input> <netscape_output>")
    else:
        json_to_netscape(sys.argv[1], sys.argv[2])
